---
- hosts: all
  become: true
  become_user: root
  gather_facts: yes
   
  tasks:
    - name: test ssh connection
      command: ls -altr
      
    - name: Run shell script
      script: ./sshall.sh {{ arg1 }} {{ arg2 }}
